sudo: false
env:
  - NEO4J_VERSION="3.1.1"
language: java
before_install:
  - wget dist.neo4j.org/neo4j-community-${NEO4J_VERSION}-unix.tar.gz
  - tar -xzf neo4j-community-${NEO4J_VERSION}-unix.tar.gz
  - neo4j-community-${NEO4J_VERSION}/bin/neo4j start
before_script:
  - neo4j-community-3.1.1/bin/neo4j-admin set-initial-password secret
jdk:
  - oraclejdk8
script:
  - test/run.sh
notifications:
  slack:
    secure: j2oDWgnZm02HH+hYLLR7h0WEnQmZzxu5ldmjfNomI1ffuQdkdoWwuVJ4+/t3pUAYGrRwIqe0o+qQhdLIipjTiO/ATTTx+x5qua24qU3xjQiXi9G9TLqDWmRTuzOTdrB8hDjyb1Bhg9+wjdOPlU1phFYr8gYNrSlary+xbkT4cEk=
